# To build:
#
# (make sure to log into registry.redhat.io)
# docker build --file Dockerfile --tag harbor.example.com/lsudo/sudoadmin:latest . --build-arg https_proxy=http://10.0.0.250:80 --build-arg http_proxy=http://10.0.0.250:80
# or
# podman build --file Dockerfile --tag woodnas.local/sudoadmin:latest .
#
# podman push woodnas.local/sudoadmin
#
# Note:  This is the Dockerfile used by the devops pipeline

FROM python:latest
ENV https_proxy http://10.0.0.250:80
ENV http_proxy http://10.0.0.250:80
ENV no_proxy 10.0.0.0/8,.example.com,.mercy.net

ENV TZ America/Chicago
ENV DEBIAN_FRONTEND noninteractive

RUN apt autoremove
RUN apt autoclean -y

RUN apt-get update
# RUN apt install software-properties-common -y
# RUN apt-get install python3-pip libsasl2-dev python-dev libldap2-dev libssl-dev libnss-ldap libpam-ldap ldap-utils -y
RUN apt-get install python3-pip libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev libnss-ldap libpam-ldap -y

RUN apt-get upgrade -y
ENV PYTHONUNBUFFERED 1


# ADD certificates/root/* /usr/local/share/ca-certificates/
# RUN update-ca-certificates

RUN pip install git+https://github.com/jcrist/msgspec.git@main
ADD application/requirements.txt .
RUN pip install -r requirements.txt

USER root
RUN mkdir -p /app
COPY application/ /app

WORKDIR /app

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]
EXPOSE 8000
